---
- name: Block IP on Cisco IOS Core
  hosts: Router
  gather_facts: no

  vars:
    ansible_user: "your_username"
    ansible_password: "your_password"
    my_items:
      - "192.168.40.100"
      - "192.168.1.2"
      # Add more IPs to block if needed

  tasks:
    - name: Delete ACL
      cisco.ios.ios_config::
        lines:
          - "no access-list Block_IP_ACL"
      

    - name: Create ACL to block IPs
      cisco.ios.ios_config::
        lines:
          - "access-list standard Block_IP_ACL deny host {{ item }}"
      loop: "{{ my_items }}"
      

    - name: Permit any
      ios_config:
        lines:
          - "access-list standard Block_IP_ACL permit any any"
      

    - name: Apply ACL to an interface
      cisco.ios.ios_config::
        lines:
          - "interface range e1/0-3,e2/0-3,e3/0-3"
          - "ip access-group Block_IP_ACL in"      

    - name: Save the running configuration
      ios_command:
        commands:
          - "write memory"
      
