---
- name: Block IP on Cisco IOS devices
  hosts: Core
  gather_facts: no
  connection: network_cli
  vars_prompt:
    - name: source_ip
      prompt: "Enter the source IP to block (e.g., 192.168.0.10)"
      private: no

  tasks:
    - name: Create ACL to block IP
      ios_acl:
        name: MyACL
        rules:
          - action: deny
            proto: ip
            src: "{{ source_ip }}"
        state: present
