---
- name: Block IP on Cisco IOS device
  hosts: Core
  vars:
    bien: test
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Create ACL to block IP
      cisco.ios.ios_acls:
        name: MyACL
        rules:
          - action: deny
            proto: ip
            src: {{ bien }}
            state: present
