---
- name: Block IP Source using User Input
  hosts: checkpoint
  gather_facts: no
  connection: httpapi

  vars_prompt:
    - name: source_ip
      private: no

  tasks:
    - name: Add Access Rule to Block IP
      check_point_mgmt:
        command: add-access-rule
        position: bottom
        layer: "Network"
        name: "Block IP Rule"
        action: Drop
        source: "{{ source_ip }}"
        destination: "any"
