---
- name: Block IP on Cisco IOS device
  hosts: Core
  vars:
    bien: "192.168.40.100"
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Create ACL to block IP
      ios_acl:
        name: MyACL
        rules:
          - action: deny
            proto: ip
            src: "{{ bien }}"
            state: present
