---
- name: Block IP on Cisco IOS devices
  hosts: all
  gather_facts: no

  vars:
    ansible_user: "your_username"
    ansible_password: "your_password"
    my_items:
      - "192.168.40.100"
      - "192.168.1.2"
      # Add more IPs to block if needed

  tasks:
    - name: Delete ACL if exists
      ios_config:
        lines:
          - "no access-list Block_IP_ACL"
      ignore_errors: yes
      
    - name: Create ACL to block IPs
      ios_config:
        lines:
          - "access-list standard Block_IP_ACL"
          - "deny host {{ item }}"
      loop: "{{ my_items }}"
      register: acl_result
      
    - name: Apply ACL to an interface
      ios_config:
        lines:
          - "interface Ethernet0/0"
          - "ip access-group Block_IP_ACL in"
      when: acl_result is not failed and ansible_network_os == "ios"
      
    - name: Save the running configuration
      ios_command:
        commands:
          - "write memory"
      when: acl_result is not failed and ansible_network_os == "ios"
