---
- name: Get IP and Hostname
  hosts: all
  gather_facts: yes  
  tasks:
    - name: Create ACL to block IPs
      ios_config:
        lines:
          - "access-list 10 deny host 192.168.40.100"

