---
- name: Run ipconfig command on Windows
  hosts: DC
  gather_facts: no

  tasks:
    - name: Run ipconfig command
      win_shell: |
        cd "C:\Users\Administrator\Downloads\loki"
        .\loki.exe -p "C:\Users\Administrator\Downloads" --pesieveshellc --logfolder "\loki_logs\"     
      register: run_output

    - name: Display ipconfig output
      debug:
        var: run_output.stdout_lines
